export const SD_ALLOW_DELETE_ENV_KEY = "SD_ALLOW_DELETE";
export const SD_PASSWORD_ENV_KEY = "SD_PASSWORD";
export const SD_PASSWORD_SALT_ENV_KEY = "SD_PASSWORD_SALT";
export const SD_IMAGES_ROOT_ENV_KEY = "SD_IMAGES_ROOT";
export const SD_CACHE_DIR_ENV_KEY = "SD_CACHE_DIR";
